### ISSUE TITLE
Issues sending transaction to solana chain 

### ISSUE THREAD

**Issue by kasahh** [SuperteamDAO/solathon#14]
I am trying to send a transaction to the Solana chain but I am not sure how to implement the instruction data i received from an NFT marketplace api. 

The instruction is in this format:
{"tx": {"type": "Buffer","data": [ 1,0, 9,12,185,0,..........0]},"txSigned": {"type": "Buffer","data": [ 1, 0,0,.......0]}}

How do I use this instruction data with Solathon to sign and successfully complete the transaction?

**Comment by RevTpark** [comment]
custom_instruction = {
    'program_id': PublicKey("your_program_id"),
    'data': instruction_data,
}

transaction = Transaction(instructions=[transfer_instruction, custom_instruction], signers=[sender])
@GitBolt can you confirm if this would work for this particular case?

**Comment by GitBolt** [comment]
yes that should work. but i think the main goal is to get that `instruction_data` here in solathon. the person got the buffer transaction data and now wants to load it in solathon. atm there is default or in built function to do it

**Comment by GitBolt** [comment]
Closing this for now as the OP seems inactive. Feel free to reopen! cc: @kasahh
