### ISSUE TITLE
ValueError when using a seed co create a keypair

### ISSUE THREAD

**Issue by chigozieokoroafor** [SuperteamDAO/solathon#15]
Tried creating a keypair from a byte seed using solathon, but an error was returned :
"ValueError: Invalid character '\x00' " was the error being returned
![Screenshot from 2022-07-09 15-48-06](https://user-images.githubusercontent.com/48325147/178110936-7fb14741-e11e-4b65-9daa-bc797ae82959.png)

**Comment by RevTpark** [comment]
@chigozieokoroafor can you check your private key once, cause this issue seems to be related to an incorrectly configured private key. Mostly containing blanks in the key. Can you confirm if the key is correct and valid?

**Comment by GitBolt** [comment]
Closing due to inactive. Feel free to re-open if you face further issues or have any questions @chigozieokoroafor
