### ISSUE TITLE
Active Status?

### ISSUE THREAD

**Issue by kcal-outside** [SuperteamDAO/solathon#17]
What is the current maintained status of this? I see an issue fix not merged from 7 days ago...

**Comment by GitBolt** [comment]
Apologize for this! Did not get the email notification for it weirdly. Merged it.
I was quite busy with other projects and recently school exams. It's hard to maintain the entire package as a single core maintainer, but will get back to action this month!

**Comment by GitBolt** [comment]
I obviously know I failed to get back to action, don't @ me on this to whoever is seeing
