### ISSUE TITLE
Error in path (building) -> args -> lamports struct

### ISSUE THREAD

**Issue by Jobians** [SuperteamDAO/solathon#18]
I'm trying to create script for sending Solana but error occurs:

> Error in path (building) -> args -> lamports struct

This error occur in `lamports=amount` but if I enter `lamports=1000` the error will not occur.

My code:

`def solsend(private_key,public_key,amount):
    try:
        client = Client("https://api.mainnet-beta.solana.com")
        sender = Keypair().from_private_key(private_key)
        receiver = PublicKey(public_key)
        instruction = transfer(
            from_public_key=sender.public_key,
            to_public_key=receiver, 
            lamports=amount
        )
        transaction = Transaction(instructions=[instruction], signers=[sender])
        result = client.send_transaction(transaction)
        transaction_id = result['result']
        if transaction_id != None:
            return '{ "status": "ok", "transaction_id": "'+str(transaction_id)+'"}'
        else:
            return '{ "status": "fail", "result": "'+str(result)+'"}'
    except Exception as e:
        print(amount)
        return '{ "status": "error", "message": "'+str(e)+'"}'`

I'm trying to add `amount` value to `lamports`.

**Comment by GitBolt** [comment]
hey @Jobians, can you send formatted code? hard to read here. and what's the value of `amount`?

**Comment by Jobians** [comment]
amount value is 100

**Comment by Jobians** [comment]
Check code here
https://gist.github.com/Jobians/cac3d99ce242cdd5d10a44862ab352d9

**Comment by GitBolt** [comment]
can you show me the value of `result` variable? print it before the if conditions

**Comment by Jobians** [comment]
The script stop at `lamports=amount` and throw this error 

> Error in path (building) -> args -> lamports struct

**Comment by GitBolt** [comment]
so when you enter 1000 hardcoded in lamports then it works, but when you are using the amount parameter, it does not right? that means both values are different in some way, print out "amount" first and see if it's not a string or anything

**Comment by Jobians** [comment]
It showing this
`{ "status": "ok", "amount": "100"}`

**Comment by GitBolt** [comment]
it should be int(amount["amount"]) in the lamports then

lamports parameter accepts integer but this is an object so you gotta parse that

**Comment by Jobians** [comment]
The amount value is 100, I just added `{ "status": "ok", "amount": "100"}` to avoid flask error

**Comment by Jobians** [comment]
I fix my renaming amount variable with something else like amo .

I think your script already define amount variable with something.
