### ISSUE TITLE
Add: Repr to all type objects

### ISSUE THREAD

**Issue by GitBolt** [SuperteamDAO/solathon#54]
Right now, most of the objects do not have a __repr__ method, and hence when they are printed, the object is printed without any meaningful info. 

I have added repr to some classes in this section of this commit: https://github.com/SuperteamDAO/solathon/commit/163e2332c6f4fae39aa751853fa91ca9e039a03a#diff-1eb89ae756d42de1fd915f6f4ad348bc01edf78519a3e788c7aae9b723c86ff2

All other classes need to have a similar method as well.

**Comment by nithinexe** [comment]
Is someone working on this?

**Comment by GitBolt** [comment]
Nope! If you want, feel free to take it up @nithinexe!

**Comment by nithinexe** [comment]
Cool, would you assign? or i can start working.

**Comment by A91y** [comment]
Hi @GitBolt, I would like to contribute to this issue.

**Comment by GitBolt** [comment]
Assigned to you as well! @A91y
