### ISSUE TITLE
Missing Documentation for get_transaction Method

### ISSUE THREAD

**Issue by gigabit-eth** [SuperteamDAO/solathon#58]
I've noticed that the documentation for the "get_transaction" method is missing on the [official documentation page](https://solathon.vercel.app/clients/client#get_transaction). When attempting to access information for this method, the link leads to no content, whereas adjacent methods have detailed explanations.

This absence makes it hard to understand and utilize the get_transaction method effectively, impacting the simplicity of the library. Could you please add the missing documentation for this method?

**Comment by GitBolt** [comment]
Thanks for pointing it out! It has been added now.
