### ISSUE TITLE
How to send SPL token?

### ISSUE THREAD

**Issue by chiwalfrm** [SuperteamDAO/solathon#60]
I see that I can send SOL very easily like this:

```
transfer: Transaction = create_transfer(client, lawrenceprivate_keysol, {
        "recipient": nathanpublic_keysol,
        "amount": 0.00001,
        "reference": lawrenceprivate_keysol.public_key}
)
client.send_transaction(transfer)
```

But how do I send SPL token instead?  For example I want to send USDC with mint address "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

I can't figure it out from reading the documentation

**Comment by GitBolt** [comment]
Hi! Unfortunately we don't support SPL right now. You would want to use [Solana.py](https://github.com/michaelhly/solana-py) for that
