### ISSUE TITLE
Error -32600: Encoded binary (base 58) data should be less than 128 bytes, please use Base64 encoding.

### ISSUE THREAD

**Issue by hotamago** [SuperteamDAO/solathon#62]
Add type Dict for Commitment please

**Comment by GitBolt** [comment]
hey @hotamago, been a while since i opened the code and hence a bit confused. can you share your relevant code so that I can reproduce and fix this? thanks

**Comment by GitBolt** [comment]
Merged your change. Thank you! https://github.com/SuperteamDAO/solathon/pull/63
