### ISSUE TITLE
Extra parameters for get_signatures_for_address: Until, before and limit

### ISSUE THREAD

**Issue by andmart** [SuperteamDAO/solathon#64]
Hi,

I can't see a way to get older signatures because the current get_signatures_for_address implementation does not use the parameters until, before and limit.
Am I missing anything here or the method was really implemented without these parameters?

Thanks in advance

https://solana.com/docs/rpc/http/getsignaturesforaddress

**Comment by GitBolt** [comment]
hey @andmart, good catch! it was missed. i just published a new stable version. feel free to re-install the package and let me know if it is fine for you
