### ISSUE TITLE
solathon.utils.RPCRequestError: Failed to fetch data from RPC endpoint. Error -32002: Transaction simulation failed: Error processing Instruction 1: custom program error: 0xbc0

### ISSUE THREAD

**Issue by tigermumu** [SuperteamDAO/solathon#69]
Could anyone provide some document about solathon interface with program? fork, modified and broad some Tx from block explorer

**Comment by GitBolt** [comment]
Hi @tigermumu. Unfortunately Solathon does not have Solana program support as of now. For that, I would recommend using [Anchor.py](https://kevinheavey.github.io/anchorpy/).

**Comment by tigermumu** [comment]
Oh, I like solathon more simple and document goog to read. Anchor.py is already read, but make me buzz...

**Comment by GitBolt** [comment]
Thanks! Yeah that was the aim with Solathon. Although it hasn't been able to developer further to support more complex actions like programs and spl tokens yet.
