### ISSUE TITLE
in get_recent_blockhash "getRecentBlockhash" Method not found 

### ISSUE THREAD

**Issue by QingKuangZi** [SuperteamDAO/solathon#76]
solathon.utils.RPCRequestError: Failed to fetch data from RPC endpoint. Error -32601: Method not found

**Comment by skrtdev** [comment]
getLatestBlockhash should be used instead (solana core 2.0 i think), but i found many other bugs in the async version of the client

**Comment by GitBolt** [comment]
the issue is fixed in the recent release
