### ISSUE TITLE
No option to deserialize encoded transaction

### ISSUE THREAD

**Issue by chigozie-coder** [SuperteamDAO/solathon#84]
I will like to deserialize a serialized base 58 format transaction.

This is equivalent to **transaction.deserialize** in Solana py.

I need help thanks

**Comment by mircial** [comment]
Transaction.from_buffer()

**Comment by chigozie-coder** [comment]
> Transaction.from_buffer()

Thanks, but how do I do something like this Solana py equivalent.
I don't have idea how to send raw transaction.
Please help. Thanks
```python
# ... under a function
if tx_type == "legacy":
                transaction = Transaction.from_bytes(serialized_tx)
                transaction.sign([keypair], blockhash)
            else:
                return print("TX type not supported :/")

            signature = await client.send_raw_transaction(bytes(transaction))
            
```

**Comment by mircial** [comment]
tx = Transaction.from_buffer(serialized_tx, [keypair]) # make sure the serialized_tx is bytes type
client.send_transaction(tx)

**Comment by GitBolt** [comment]
Did this work? @chigozie-coder 
If so, you can close the issue, otherwise, feel free to ask further.

**Comment by chigozie-coder** [comment]
It worked thanks
